# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iH6F7MBLUY-ef_BFHsp25FfkEN0l3cDe
"""

a= 2
print(a,type(2))
print()
a1= 5.2
print(a1,type(a1))
print()
a2= 1+2j
print(a2,type(a2))
print()
a3= "Siddhant"
print(a3,type(a3))
print()
lst= [1,'Siddhant', -2, 3.7]
print(lst, type(lst))
print()
tup= (1, 2, -3, 9.4, "Siddhant")
print(tup,type(tup))
print()
d= {1:"Siddhant",2:"Naitik",3:"Aayush",4:"Amit",5:"Mayank",6:"Yash"}
print(d,type(d))
print()
s= {1, 2, 8.4, -4, "Siddhant", "Sharma"}
print(s,type(s))