# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OwFUe9FqXTCamgIHM26AbbUSlaBxQV0S
"""

temp= int(input())
for i in range(temp):
    n= input()
    sum= int(n[0])+int(n[len(n)-1])
    print(sum)