# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OwFUe9FqXTCamgIHM26AbbUSlaBxQV0S
"""

temp= int(input())
for i in range(temp):
    a,b= input().split()
    print(int(a)%int(b))